//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSevenDayNight.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyStats()
        {
            this.CompanyStatsTranslations = new HashSet<CompanyStatsTranslations>();
        }
    
        public int StatId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Value { get; set; }
        public string Unit { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyStatsTranslations> CompanyStatsTranslations { get; set; }
    }
}
