//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSevenDayNight.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTranslations
    {
        public int TranslationId { get; set; }
        public int EmployeeId { get; set; }
        public string LanguageCode { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string NameSurname { get; set; }
        public string Job { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
