//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSevenDayNight.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DayNightDbEntities : DbContext
    {
        public DayNightDbEntities()
            : base("name=DayNightDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCategory> TblCategory { get; set; }
        public virtual DbSet<TblProduct> TblProduct { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Crausel> Crausel { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Faq> Faq { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<CompanyStats> CompanyStats { get; set; }
        public virtual DbSet<About> About { get; set; }
    }
}
